# Generated by Django 3.0.2 on 2020-03-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200310_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_images/thumbnail_pics/default.jpg', upload_to=''),
        ),
    ]
