# Generated by Django 3.0.2 on 2020-03-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200310_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='yoo_shi_jin.jpg', upload_to=''),
        ),
    ]
