# Generated by Django 3.0.2 on 2020-03-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200311_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/profile_images/default.jpg', upload_to=''),
        ),
    ]
