# Generated by Django 3.0.2 on 2020-03-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200311_1044'),
        ('accounts', '0013_auto_20200311_0847'),
    ]

    operations = [
    ]
