# Generated by Django 3.0.4 on 2020-07-15 13:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
