# Generated by Django 3.0.2 on 2020-07-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('ratings', models.FloatField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('reviews', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='thumbnail_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='no_of_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
