# Generated by Django 3.0.4 on 2020-07-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0002_auto_20200720_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isfeatured',
            field=models.BooleanField(default=False),
        ),
    ]
