# Generated by Django 3.0.4 on 2020-03-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0003_auto_20200225_0856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artisan',
            unique_together={('contact',)},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category',)},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('artisan_id', 'category', 'name')},
        ),
    ]
