# Generated by Django 3.0.4 on 2020-07-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isfeatured',
            field=models.BooleanField(default=False),
        ),
    ]
