# Generated by Django 3.0.4 on 2020-07-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0006_product_isfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='thumbnail_pics'),
        ),
    ]
