# Generated by Django 3.0.2 on 2020-07-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
