# Generated by Django 3.0.2 on 2020-07-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('count', models.IntegerField()),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
