# Generated by Django 3.0.4 on 2020-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200721_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Recieved', 'Recieved'), ('Waiting', 'Waiting'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Delivered', max_length=10),
        ),
    ]
